name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Shubham Tatvamasi"
          git config user.email "shubhamtatvamasi@gmail.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.0

      # - name: Add helm repo
      #   run: |
      #     helm repo add orc8r https://shubhamtatvamasi.github.io/magma-charts-2-3-2022-v2

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
